# Generated by Django 4.0.3 on 2022-03-13 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_sales_webapp', '0002_transactions_quantity_remove_transactions_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='product',
            field=models.ManyToManyField(to='shop_sales_webapp.product'),
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='product',
        ),
        migrations.AddField(
            model_name='transactions',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='shop_sales_webapp.product'),
            preserve_default=False,
        ),
    ]
